from typing import Optional


TICKER_DOMAINS = {
    'AAPL': 'apple.com',
    'AMZN': 'amazon.com',
    'ASML': 'asml.com',
    'ADI': 'analog.com',
    'AMAT': 'appliedmaterials.com',
    'AVGO': 'broadcom.com',
    'ARM': 'arm.com',
    'BABA': 'alibaba.com',
    'BHP': 'bhp.com',
    'BMWYY': 'bmwgroup.com',
    'BP': 'bp.com',
    'BYDDF': 'byd.com',
    'CRM': 'salesforce.com',
    'CSCO': 'cisco.com',
    'CDNS': 'cadence.com',
    'CVX': 'chevron.com',
    'CRWD': 'crowdstrike.com',
    'DELL': 'dell.com',
    'F': 'ford.com',
    'GOOG': 'google.com',
    'GOOGL': 'google.com',
    'HMC': 'honda.com',
    'IBM': 'ibm.com',
    'INTC': 'intel.com',
    'INFY': 'infosys.com',
    'KLAC': 'kla.com',
    'LRCX': 'lamresearch.com',
    'JPM': 'jpmorganchase.com',
    'KO': 'coca-cola.com',
    'MA': 'mastercard.com',
    'MCD': 'mcdonalds.com',
    'META': 'meta.com',
    'MS': 'morganstanley.com',
    'MSFT': 'microsoft.com',
    'MU': 'micron.com',
    'NOW': 'servicenow.com',
    'NIO': 'nio.com',
    'NKE': 'nike.com',
    'NFLX': 'netflix.com',
    'NVDA': 'nvidia.com',
    'PANW': 'paloaltonetworks.com',
    'ORCL': 'oracle.com',
    'PEP': 'pepsico.com',
    'PG': 'pg.com',
    'PFE': 'pfizer.com',
    'RIO': 'riotinto.com',
    'SAP': 'sap.com',
    'SNPS': 'synopsys.com',
    'SBUX': 'starbucks.com',
    'SHEL': 'shell.com',
    'SIEGY': 'siemens.com',
    'SONY': 'sony.com',
    'SPCX': 'simplify.us',
    'SPACEX': 'spacex.com',
    'STLA': 'stellantis.com',
    'TXN': 'ti.com',
    'TMC': 'metals.co',
    'TM': 'toyota.com',
    'TSLA': 'tesla.com',
    'TSM': 'tsmc.com',
    'TTE': 'totalenergies.com',
    'UL': 'unilever.com',
    'UNH': 'unitedhealthgroup.com',
    'V': 'visa.com',
    'VWAGY': 'volkswagen.com',
    'WMT': 'walmart.com',
    'HPE': 'hpe.com',
    'XOM': 'exxonmobil.com',
    'Z74.SI': 'singtel.com',
}


def logo_url_for_ticker(ticker: Optional[str]) -> Optional[str]:
    if not ticker:
        return None
    domain = TICKER_DOMAINS.get(ticker.upper())
    if not domain:
            return None
    return f'https://www.google.com/s2/favicons?domain={domain}&sz=128'